"""Add nullable columns to episode table

Revision ID: 500e4ad13d9f
Revises: e97c7cd72f6b
Create Date: 2024-09-08 15:05:26.757322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500e4ad13d9f'
down_revision = 'e97c7cd72f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('player_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('publish_time',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('episode_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('permalink',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.alter_column('permalink',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('episode_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('publish_time',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('player_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
