"""Initial migration.

Revision ID: e97c7cd72f6b
Revises: 
Create Date: 2024-09-08 15:03:45.967338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97c7cd72f6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.alter_column('permalink',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.alter_column('permalink',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
